name: Release to NuGet

on:
  release:
    types: [published]

permissions:
  contents: write
  
env:
  project_path: SqlBulkCopyHelper/SqlBulkCopyHelper.csproj

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Setup .Net
        uses: actions/setup-dotnet@v5
        
      - name: Restore
        run: dotnet restore ${{ env.project_path }}
        
      - name: Build
        run: dotnet build ${{ env.project_path }} --configuration Release --no-restore
        
      - name: Pack
        run: dotnet pack ${{ env.project_path }} --configuration Release --no-build --output out /p:PackageVersion=${{ github.event.release.tag_name }}
        
      - name: Upload nuget to release
        run: gh release upload ${{ github.event.release.tag_name }} out/SqlBulkCopyHelper.${{ github.event.release.tag_name }}.nupkg
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
          shell: bash